name: prepend changelog

on: workflow_dispatch

jobs:
  prepend-changelog:
    name: Append Change Log
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Prepend changelog to CHANGELOG.md
        run: |
          VERSION="v3.8.0"
          CHANGELOG_FILE="docs/changelogs/$VERSION.md"
          MAIN_CHANGELOG="CHANGELOG.md"

          if [ ! -f "$CHANGELOG_FILE" ]; then
            echo "No changelog found for $VERSION"
            exit 1
          fi

          TMP_FILE=$(mktemp)

          echo "# $VERSION" > "$TMP_FILE"
          cat "$CHANGELOG_FILE" >> "$TMP_FILE"
          echo "" >> "$TMP_FILE"
          cat "$MAIN_CHANGELOG" >> "$TMP_FILE"
          mv "$TMP_FILE" "$MAIN_CHANGELOG"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "docs/changelog-update-v3.8.0"
          commit-message: "[skip ci] docs: prepend changelog for v3.8.0"
          title: "[Docs] Prepend changelog for v3.8.0"
          body: "Automated changelog update for v3.8.0"
          base: main
          delete-branch: true
          labels: automerge

      - name: Automerge PR
        if: steps.cpr.outputs.pull-request-url
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_METHOD: "squash"
