name: prepend changelog

on: workflow_dispatch

jobs:
  prepend-changelog:
    name: Append Change Log
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Prepend changelog to CHANGELOG.md
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          CHANGELOG_FILE="docs/changelogs/$VERSION.md"
          MAIN_CHANGELOG="CHANGELOG.md"

          if [ ! -f "$CHANGELOG_FILE" ]; then
            echo "No changelog found for $VERSION"
            exit 1
          fi

          TMP_FILE=$(mktemp)

          echo "# $VERSION" > "$TMP_FILE"
          cat "$CHANGELOG_FILE" >> "$TMP_FILE"
          echo "" >> "$TMP_FILE"
          cat "$MAIN_CHANGELOG" >> "$TMP_FILE"
          mv "$TMP_FILE" "$MAIN_CHANGELOG"

      - name: Commit updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v6
        id: auto-commit-action
        with:
          commit_message: "[skip ci] docs: prepend ${{ env.TAG_NAME }} changelog to CHANGELOG.md"
          file_pattern: CHANGELOG.md
          commit_user_name: "pytorch_optimizer-actions[bot]"
          commit_user_email: "pytorch_optimizer-actions[bot]@users.noreply.github.com"
          push_options: "--force"

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_det
