name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  prepend-changelog:
    name: Prepend Change Log
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Prepend changelog to CHANGELOG.md
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          CHANGELOG_FILE="docs/changelogs/$VERSION.md"
          MAIN_CHANGELOG="CHANGELOG.md"

          if [ ! -f "$CHANGELOG_FILE" ]; then
            echo "No changelog found for $VERSION"
            exit 1
          fi

          TMP_FILE=$(mktemp)

          echo "# $VERSION" > "$TMP_FILE"
          echo "" >> "$TMP_FILE"
          cat "$CHANGELOG_FILE" >> "$TMP_FILE"
          echo "" >> "$TMP_FILE"
          cat "$MAIN_CHANGELOG" >> "$TMP_FILE"
          mv "$TMP_FILE" "$MAIN_CHANGELOG"

      - name: Create Pull Request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "docs/changelog-update-${{ steps.get_version.outputs.VERSION }}"
          commit-message: "[skip ci] docs: prepend changelog for ${{ steps.get_version.outputs.VERSION }}"
          title: "[Docs] Prepend changelog for ${{ steps.get_version.outputs.VERSION }}"
          body: "Automated changelog update for ${{ steps.get_version.outputs.VERSION }}"
          base: main
          delete-branch: true
          labels: automerge
          token: ${{ secrets.GH_TOKEN }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: pytorch-optimizer ${{ github.ref }}
          body_path: docs/changelogs/${{ steps.get_version.outputs.VERSION }}.md
          draft: false
          prerelease: false

  deploy:
    name: Deploy
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip --disable-pip-version-check install --no-compile poetry
          pip --disable-pip-version-check install --no-compile -r requirements.txt

      - name: Publish package to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
